### ISSUE TITLE
orca or kaleido not available in my embedded system

### ISSUE THREAD

**Issue by Pascal66** [yutaka-shoji/shimeri#1]
**Describe the bug**
orca or kaleido not available in my embedded system
(headless so no chromium)
**Additional context**
Switch to matplotlib ?

**Comment by yutaka-shoji** [comment]
Thank you for your comment.  
The web application using this package (URL: https://shimeri-web.vercel.app) depends on plotly, so I am not considering switching the backend for drawing to matplotlib.
Could you provide more detailed information about the environment where this issue is occurring?
